from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
ASSETS_DIR = BASE_DIR / "assets"

LANDMARK_CSV_PATH = DATA_DIR / "landmarks.csv"
MODEL_PATH = DATA_DIR / "model.pkl"
DATABASE_PATH = DATA_DIR / "sessions.db"
SIGN_REFERENCE_PATH = ASSETS_DIR / "sign_reference.png"

CAMERA_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
TARGET_FPS = 20
MIRROR_CAMERA = True

MEDIAPIPE_MAX_NUM_HANDS = 2
MEDIAPIPE_DETECTION_CONFIDENCE = 0.7
MEDIAPIPE_TRACKING_CONFIDENCE = 0.6

FEATURE_INCLUDE_DISTANCES = True
FEATURE_INCLUDE_ANGLES = True
FEATURE_INCLUDE_FINGER_FLAGS = True

COLLECTION_MIN_SAMPLES_PER_CLASS = 100
COLLECTION_RECOMMENDED_SAMPLES_PER_CLASS = 200
COLLECTION_SAVE_COOLDOWN_SECONDS = 0.06

CLASSIFIER_TYPE = "random_forest"
TEST_SIZE = 0.2
RANDOM_STATE = 42
RANDOM_FOREST_ESTIMATORS = 180
CONFIDENCE_THRESHOLD = 0.55

TTS_ENABLED = True
TTS_RATE = 165
TTS_VOLUME = 1.0
TTS_VOICE_INDEX = 0
TTS_SPEAK_WORDS_AUTOMATICALLY = False

STABLE_FRAME_WINDOW = 9
LETTER_HOLD_SECONDS = 0.8
CONFIRM_COOLDOWN_SECONDS = 0.25

SPACE_LABELS = {"SPACE", "space", "_"}
DELETE_LABELS = {"DELETE", "delete", "DEL", "del", "BACKSPACE", "backspace"}
NOTHING_LABELS = {"NOTHING", "nothing", "IDLE", "idle"}

AIR_DRAW_CANVAS_ALPHA = 0.85
AIR_DRAW_MIN_POINT_DISTANCE = 8
AIR_DRAW_BRUSH_THICKNESS = 6
AIR_DRAW_ERASER_THICKNESS = 28
AIR_DRAW_OUTPUT_DIR = DATA_DIR / "air_drawings"

VOCABULARY = [
    "HELLO",
    "HELP",
    "WATER",
    "FOOD",
    "PAIN",
    "DOCTOR",
    "YES",
    "NO",
    "STOP",
    "THANKS",
    "PLEASE",
    "SORRY",
    "GOOD",
    "BAD",
    "HOME",
    "SCHOOL",
    "WORK",
    "NAME",
    "AGE",
    "MEDICINE",
    "FAMILY",
]
